# Generated by Django 3.0.6 on 2024-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0014_followlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrating',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
